/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesIdRouteImport } from './routes/movies.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedManagerRouteImport } from './routes/_authenticated/manager'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedManagerIndexRouteImport } from './routes/_authenticated/manager.index'
import { Route as AuthenticatedTicketsBookingIdRouteImport } from './routes/_authenticated/tickets.$bookingId'
import { Route as AuthenticatedManagerShowsRouteImport } from './routes/_authenticated/manager.shows'
import { Route as AuthenticatedManagerMoviesRouteImport } from './routes/_authenticated/manager.movies'
import { Route as AuthenticatedBookShowIdRouteImport } from './routes/_authenticated/book.$showId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIdRoute = MoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerRoute = AuthenticatedManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManagerIndexRoute =
  AuthenticatedManagerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedTicketsBookingIdRoute =
  AuthenticatedTicketsBookingIdRouteImport.update({
    id: '/tickets/$bookingId',
    path: '/tickets/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManagerShowsRoute =
  AuthenticatedManagerShowsRouteImport.update({
    id: '/shows',
    path: '/shows',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedManagerMoviesRoute =
  AuthenticatedManagerMoviesRouteImport.update({
    id: '/movies',
    path: '/movies',
    getParentRoute: () => AuthenticatedManagerRoute,
  } as any)
const AuthenticatedBookShowIdRoute = AuthenticatedBookShowIdRouteImport.update({
  id: '/book/$showId',
  path: '/book/$showId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/manager': typeof AuthenticatedManagerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/movies/$id': typeof MoviesIdRoute
  '/book/$showId': typeof AuthenticatedBookShowIdRoute
  '/manager/movies': typeof AuthenticatedManagerMoviesRoute
  '/manager/shows': typeof AuthenticatedManagerShowsRoute
  '/tickets/$bookingId': typeof AuthenticatedTicketsBookingIdRoute
  '/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/movies/$id': typeof MoviesIdRoute
  '/book/$showId': typeof AuthenticatedBookShowIdRoute
  '/manager/movies': typeof AuthenticatedManagerMoviesRoute
  '/manager/shows': typeof AuthenticatedManagerShowsRoute
  '/tickets/$bookingId': typeof AuthenticatedTicketsBookingIdRoute
  '/manager': typeof AuthenticatedManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/manager': typeof AuthenticatedManagerRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/movies/$id': typeof MoviesIdRoute
  '/_authenticated/book/$showId': typeof AuthenticatedBookShowIdRoute
  '/_authenticated/manager/movies': typeof AuthenticatedManagerMoviesRoute
  '/_authenticated/manager/shows': typeof AuthenticatedManagerShowsRoute
  '/_authenticated/tickets/$bookingId': typeof AuthenticatedTicketsBookingIdRoute
  '/_authenticated/manager/': typeof AuthenticatedManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bookings'
    | '/manager'
    | '/profile'
    | '/movies/$id'
    | '/book/$showId'
    | '/manager/movies'
    | '/manager/shows'
    | '/tickets/$bookingId'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/profile'
    | '/movies/$id'
    | '/book/$showId'
    | '/manager/movies'
    | '/manager/shows'
    | '/tickets/$bookingId'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/bookings'
    | '/_authenticated/manager'
    | '/_authenticated/profile'
    | '/movies/$id'
    | '/_authenticated/book/$showId'
    | '/_authenticated/manager/movies'
    | '/_authenticated/manager/shows'
    | '/_authenticated/tickets/$bookingId'
    | '/_authenticated/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  MoviesIdRoute: typeof MoviesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$id': {
      id: '/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof MoviesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager': {
      id: '/_authenticated/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof AuthenticatedManagerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/': {
      id: '/_authenticated/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof AuthenticatedManagerIndexRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/tickets/$bookingId': {
      id: '/_authenticated/tickets/$bookingId'
      path: '/tickets/$bookingId'
      fullPath: '/tickets/$bookingId'
      preLoaderRoute: typeof AuthenticatedTicketsBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manager/shows': {
      id: '/_authenticated/manager/shows'
      path: '/shows'
      fullPath: '/manager/shows'
      preLoaderRoute: typeof AuthenticatedManagerShowsRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/manager/movies': {
      id: '/_authenticated/manager/movies'
      path: '/movies'
      fullPath: '/manager/movies'
      preLoaderRoute: typeof AuthenticatedManagerMoviesRouteImport
      parentRoute: typeof AuthenticatedManagerRoute
    }
    '/_authenticated/book/$showId': {
      id: '/_authenticated/book/$showId'
      path: '/book/$showId'
      fullPath: '/book/$showId'
      preLoaderRoute: typeof AuthenticatedBookShowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedManagerRouteChildren {
  AuthenticatedManagerMoviesRoute: typeof AuthenticatedManagerMoviesRoute
  AuthenticatedManagerShowsRoute: typeof AuthenticatedManagerShowsRoute
  AuthenticatedManagerIndexRoute: typeof AuthenticatedManagerIndexRoute
}

const AuthenticatedManagerRouteChildren: AuthenticatedManagerRouteChildren = {
  AuthenticatedManagerMoviesRoute: AuthenticatedManagerMoviesRoute,
  AuthenticatedManagerShowsRoute: AuthenticatedManagerShowsRoute,
  AuthenticatedManagerIndexRoute: AuthenticatedManagerIndexRoute,
}

const AuthenticatedManagerRouteWithChildren =
  AuthenticatedManagerRoute._addFileChildren(AuthenticatedManagerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedManagerRoute: typeof AuthenticatedManagerRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedBookShowIdRoute: typeof AuthenticatedBookShowIdRoute
  AuthenticatedTicketsBookingIdRoute: typeof AuthenticatedTicketsBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedManagerRoute: AuthenticatedManagerRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedBookShowIdRoute: AuthenticatedBookShowIdRoute,
  AuthenticatedTicketsBookingIdRoute: AuthenticatedTicketsBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  MoviesIdRoute: MoviesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
